name: Hello World
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Depoly
    steps:
      - uses: actions/checkout@v3
      - name: Hello World
        run: echo "Hello World secret ${{ secrets.SECRET_VAR }}"
      
      - name: Ensure Docker is installed
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Checking for Docker installation..."
            echo "server: ${{ vars.EC2_HOST }}"
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing..."
              sudo yum update
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ${{ vars.EC2_USERNAME }}
            else
              echo "Docker is already installed."
            fi